### ISSUE TITLE
While connecting Plex Account suddenly Exception raised while handling the request

### ISSUE THREAD

**Issue by Richigeht** [trakt-for-plex/configuration#22] opened 2016-08-26 00:56 UTC
Hello,
I had connected my second PC to Trakt using trakt-for-plex but it did not sync. So i did try to readd my plex account now i only get Exception raised while handling the request
and no sync is done and no connection can be made :/

Any ideas? Or log files needed? Thanks!

**Comment by Richigeht** [comment] 2016-08-26 08:23
Here what I see in log files:
`    params = [node.conv(node.value)]
  File "C:\Users\jaegi\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\peewee.py", line 831, in db_value
    return value if value is None else self.coerce(value)
  File "C:\Users\jaegi\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\peewee.py", line 951, in coerce
    return coerce_to_unicode(value or '')
  File "C:\Users\jaegi\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\peewee.py", line 932, in coerce_to_unicode
    return s.decode(encoding)
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xfc in position 7: invalid start byte
2016-08-26 10:13:12,897 - root                             (2cf8) :  INFO (root:840) - 304 GET /:/plugins/com.plexapp.plugins.trakttv/messaging/function/TWVzc2FnZUtpdDpBcGk_/Y2VyZWFsMQoxCmxpc3QKMQpzMTMKb3B0aW9uLnVwZGF0ZXIwCg__/Y2VyZWFsMQoxNwpkaWN0CmRpY3QKZGljdApkaWN0CmRpY3QKZGljdApkaWN0CmRpY3QKZGljdApkaWN0CmRpY3QKZGljdApkaWN0CmRpY3QKZGljdApkaWN0CmRpY3QKMgpyMQpzNwpjaGFuZ2VzaTQKczcKYWNjb3VudDE1CnIyCnMyNgpzeW5jLmxpc3RzLmxpa2VkLnBsYXlsaXN0c3IzCnMyNQpzeW5jLmxpc3RzLndhdGNobGlzdC5tb2RlcjQKczI5CnN5bmMubGlzdHMucGVyc29uYWwucGxheWxpc3RzcjUKczEzCnN5bmMuaW50ZXJ2YWxyNgpzMjQKc3luYy5saXN0cy5wZXJzb25hbC5tb2RlcjcKczE2CnNjcm9iYmxlLmVuYWJsZWRyOApzMTcKc3luYy53YXRjaGVkLm1vZGVyOQpzMjEKc3luYy5jb2xsZWN0aW9uLmNsZWFucjEwCnMzMApzeW5jLmxpc3RzLndhdGNobGlzdC5wbGF5bGlzdHNyMTEKczE5CnN5bmMubGlicmFyeV91cGRhdGVyMTIKczE3CnN5bmMucmF0aW5ncy5tb2RlcjEzCnMyMQpzeW5jLnJhdGluZ3MuY29uZmxpY3RyMTQKczE4CnN5bmMucGxheWJhY2subW9kZXIxNQpzMjEKc3luYy5saXN0cy5saWtlZC5tb2RlcjE2CnMyMApzeW5jLmNvbGxlY3Rpb24ubW9kZTIKYjFzNApmcm9tYjFzMgp0bzIKbnM0CmZyb21uczIKdG8yCmIxczQKZnJvbWIxczIKdG8yCm5zNApmcm9tbnMyCnRvMgpuczQKZnJvbW5zMgp0bzIKYjFzNApmcm9tYjFzMgp0bzIKaTAKczQKZnJvbWkwCnMyCnRvMgpiMHM0CmZyb21iMHMyCnRvMgpiMXM0CmZyb21iMXMyCnRvMgpiMHM0CmZyb21iMHMyCnRvMgppMApzNApmcm9taTAKczIKdG8yCmkwCnM0CmZyb21pMApzMgp0bzIKbnM0CmZyb21uczIKdG8yCm5zNApmcm9tbnMyCnRvMgpuczQKZnJvbW5zMgp0b3IwCg__ (127.0.0.1) 72.00ms
2016-08-26 10:13:12,911 - sentry.errors.serializer         (3050) :  ERROR (sentry.errors.serializer:78) - 'utf8' codec can't decode byte 0xfc in position 7: invalid start byte
Traceback (most recent call last):
  File "C:\Users\jaegi\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\raven\utils\serializer\manager.py", line 76, in transform
    return repr(value)
  File "C:\Users\jaegi\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\peewee.py", line 2325, in __repr__
    sql, params = self.sql()
  File "C:\Users\jaegi\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\peewee.py", line 2835, in sql
    return self.compiler().generate_update(self)
  File "C:\Users\jaegi\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\peewee.py", line 1720, in generate_update
    return self.build_query(clauses, alias_map)
  File "C:\Users\jaegi\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\peewee.py", line 1586, in build_query
    return self.parse_node(Clause(*clauses), alias_map)
  File "C:\Users\jaegi\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\peewee.py", line 1547, in parse_node
    sql, params, unknown = self._parse(node, alias_map, conv)
  File "C:\Users\jaegi\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\peewee.py", line 1522, in _parse
    sql, params = self._parse_map[node_type](node, alias_map, conv)
  File "C:\Users\jaegi\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\peewee.py", line 1450, in _parse_clause
    node.nodes, alias_map, conv, node.glue)
  File "C:\Users\jaegi\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\peewee.py", line 1564, in parse_node_list
    node_sql, node_params = self.parse_node(node, alias_map, conv)
  File "C:\Users\jaegi\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\peewee.py", line 1547, in parse_node
    sql, params, unknown = self._parse(node, alias_map, conv)
  File "C:\Users\jaegi\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\peewee.py", line 1522, in _parse
    sql, params = self._parse_map[node_type](node, alias_map, conv)
  File "C:\Users\jaegi\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\peewee.py", line 1450, in _parse_clause
    node.nodes, alias_map, conv, node.glue)
  File "C:\Users\jaegi\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\peewee.py", line 1564, in parse_node_list
    node_sql, node_params = self.parse_node(node, alias_map, conv)
  File "C:\Users\jaegi\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\peewee.py", line 1547, in parse_node
    sql, params, unknown = self._parse(node, alias_map, conv)
  File "C:\Users\jaegi\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\peewee.py", line 1522, in _parse
    sql, params = self._parse_map[node_type](node, alias_map, conv)
  File "C:\Users\jaegi\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\peewee.py", line 1431, in _parse_expression
    rhs, rparams = self.parse_node(node.rhs, alias_map, conv)
  File "C:\Users\jaegi\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\peewee.py", line 1547, in parse_node
    sql, params, unknown = self._parse(node, alias_map, conv)
  File "C:\Users\jaegi\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\peewee.py", line 1522, in _parse
    sql, params = self._parse_map[node_type](node, alias_map, conv)
  File "C:\Users\jaegi\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\peewee.py", line 1438, in _parse_param
    params = [node.conv(node.value)]
  File "C:\Users\jaegi\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\peewee.py", line 831, in db_value
    return value if value is None else self.coerce(value)
  File "C:\Users\jaegi\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\peewee.py", line 951, in coerce
    return coerce_to_unicode(value or '')
  File "C:\Users\jaegi\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\peewee.py", line 932, in coerce_to_unicode
    return s.decode(encoding)
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xfc in position 7: invalid start byte
2016-08-26 10:13:12,924 - root                             (3050) :  INFO (root:840) - 304 GET /:/plugins/com.plexapp.plugins.trakttv/messaging/function/TWVzc2FnZUtpdDpBcGk_/Y2VyZWFsMQoxCmxpc3QKMQpzMTQKYWNjb3VudC51cGRhdGVyMAo_/Y2VyZWFsMQo4CmRpY3QKZGljdApkaWN0CmRpY3QKZGljdApkaWN0CmRpY3QKZGljdAoyCmk0CnMyCmlkcjEKczQKZGF0YTMKczEzCkFkbWluaXN0cmF0b3JzNApuYW1lcjIKczQKcGxleHI1CnM1CnRyYWt0MgpzMTQKUmljaGlfTvxybmJlcmdzOAp1c2VybmFtZXIzCnMxMwphdXRob3JpemF0aW9uMQpyNApzNQpiYXNpYzEKczIwCkRBY2FCOG1MYkx2NHB0UFlrOXc1czEwCnRva2VuX3BsZXgxCnI2CnMxMwphdXRob3JpemF0aW9uMQpyNwpzNQpvYXV0aDcKczgKRjJBQ0ExOTNzNApjb2RlczY0CjUxNDhlZjIzMTNjNTk5OTU1MjhiNDM5ZjRkNTk1MTgzZGMxZDY2YzdjMjMxNWQxNTVmMTRiYzJiY2EwYWJmNWRzMTIKYWNjZXNzX3Rva2VuczYKYmVhcmVyczEwCnRva2VuX3R5cGVpNzc3NjAwMApzMTAKZXhwaXJlc19pbnM2NAphOWYyOTdlZGI1NGE3YjIyNzZkZjY3ZjZiNDBkM2MzNTE3NGJhNTU1YWZhNjA0OTg5MGE2MDI2MjEzNTdiMTU1czEzCnJlZnJlc2hfdG9rZW5zNgpwdWJsaWNzNQpzY29wZWkxNDcyMTk5MTk5CnMxMApjcmVhdGVkX2F0cjAK (127.0.0.1) 103.00ms
`

**Comment by fuzeman** [comment] 2016-08-30 03:57
That snippet from the plugin log file doesn't really give me enough information, could you provide the complete log file after enabling debug logging ([details here](https://github.com/trakt/Plex-Trakt-Scrobbler/wiki/Log-files#debug-logging)) and attempting to re-add your Plex account again.

**Comment by Richigeht** [comment] 2016-08-30 08:47
Hello
Attached some logs  - hope something useful. Besides that this happens while updating plex to latest version (1.0.3.xxx) something... After that I cannot save /reassign my plex account anymore succesfully! Maybe you want to try that out yourself.

**Comment by Richigeht** [comment] 2016-08-30 08:49
Fuck this shit cannot even upload a zip file with logs ... please get logs here: 
https://drive.google.com/open?id=0BwYpmnvLLrqIcmhZQ082Qm9oVjQ

**Comment by fuzeman** [comment] 2016-08-31 23:22
@Richigeht 
> I had connected my second PC to Trakt using trakt-for-plex but it did not sync.

By "did not sync", do you mean:
 - your Trakt.tv profile isn't being updated while you are watching media in Plex? *(scrobbling)*
 - (or) your past history, ratings, etc.. aren't being synchronized with your Trakt.tv profile after clicking `Channels -> Trakt.tv -> Sync -> Full` in Plex/Web? *(syncing)*

As it looks like *scrobbling* is working:
```
2016-08-30 10:42:47,066 - DEBUG - request: {u'progress': 62.78, u'episode': {u'season': 1, u'number': 13, u'title': u'Getrennte Wege (2)'}, u'show': {u'title': u'Doctor Who (2005)', u'ids': {u'tvdb': 78804}, u'year': 2005}}
2016-08-30 10:42:47,068 - DEBUG - Using oauth authorization for <TraktAccount username: u'[...]'>
2016-08-30 10:42:47,069 - INFO - Starting new HTTPS connection (1): api-v2launch.trakt.tv
2016-08-30 10:42:53,589 - DEBUG - "POST /scrobble/start HTTP/1.1" 201 None
2016-08-30 10:42:53,598 - DEBUG - Action u'scrobble/start' sent, moved action to history
```

It doesn't look like any *syncs* were triggered though.

---------

The issue you encountered attempting to update your Plex.tv account appears to be caused by the plugin not handling Plex.tv usernames with unicode characters correctly (specifically the `³` character in your case).

I don't think updating your Plex.tv account will fix the main issue you are facing though, as it appears Plex.tv account authentication is working correctly already.

**Comment by Richigeht** [comment] 2016-09-01 04:47
Hello 
The "problem" is that this seems still to work on my laptop even with latest Plex as long as I don't change/update the account but on my desktop it does not allow to reassign my Plex account. 
However since I am in Italy I cannot provide further logging against the desktop right now. 

So you think even with changing my Plex account name that ain't working? It's strange because the initial linking & syncing was working though :-/

**Comment by fuzeman** [comment] 2016-09-07 23:43
Just pushed a fix for the `UnicodeDecodeError` exception to the development branch. Try linking your Plex account again after installing this version of the plugin: https://github.com/trakt/Plex-Trakt-Scrobbler/archive/develop.zip

**Comment by Richigeht** [comment] 2016-09-10 21:38
Hey, thanks a lot! I also did change the username to have no ü no anymore and it seems to work
I will  update plex tonight or so and if i have issues i will create another bug report - thanks a lot for your efforts! :)

**Closed** 2016-09-30 00:31 UTC
Labels: bug
